language: node_js
node_js:
  - v10
  - v12
  - v13
install:
  - npm install
test:
  - npm run lint
  - npm run test

jobs:
  include:
  - stage: npm Deployment
    deploy:
      edge: true
      provider: npm
      skip_cleanup: true
      email: "$NPM_EMAIL"
      api_key: "$NPM_TOKEN"
      on:
        tags: true
